# Generated by Django 4.1.7 on 2023-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(default=None, max_length=255)),
                ('lastname', models.TextField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=255)),
                ('comments', models.TextField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.CreateModel(
            name='datetime1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time12', models.TextField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'datetime1',
            },
        ),
    ]
