# Generated by Django 4.1.7 on 2023-03-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='comments',
            new_name='comment',
        ),
    ]
