# Generated by Django 4.1.7 on 2023-03-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0002_rename_comments_contactus_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='signupform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(default=None, max_length=255)),
                ('lname', models.TextField(default=None, max_length=255)),
                ('gmail', models.EmailField(default=None, max_length=255)),
                ('mobile', models.BigIntegerField(default=None, max_length=255)),
                ('uname', models.TextField(default=None, max_length=255)),
                ('psswrd', models.TextField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'signupform',
            },
        ),
    ]
