# Generated by Django 4.1.7 on 2023-03-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0003_signupform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='mobile',
            field=models.BigIntegerField(default=None),
        ),
    ]
