# Generated by Django 4.1.7 on 2023-03-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0004_alter_signupform_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupform',
        ),
    ]
