# Generated by Django 4.1.7 on 2023-03-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0006_signupfm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signupfm',
        ),
    ]
