# Generated by Django 4.1.7 on 2023-03-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0008_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
    ]
