# Generated by Django 4.1.7 on 2023-03-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0010_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
