# Generated by Django 4.1.7 on 2023-03-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0011_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='signingup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(default=None, max_length=255)),
                ('lname', models.TextField(default=None, max_length=255)),
                ('gmail', models.EmailField(default=None, max_length=255)),
                ('mobile', models.BigIntegerField(default=None)),
                ('username', models.TextField(default=None, max_length=255)),
                ('password', models.TextField(default=None, max_length=255)),
            ],
            options={
                'db_table': 'signingup',
            },
        ),
    ]
