# Generated by Django 4.1.7 on 2023-03-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdp', '0012_signingup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signingup',
            old_name='password',
            new_name='psswrd',
        ),
        migrations.RenameField(
            model_name='signingup',
            old_name='username',
            new_name='uname',
        ),
    ]
