from django.urls import path
from . import views
urlpatterns=[
path('',views.function20),
    path('home/',views.function2,name='home'),
    path('index/',views.function1,name='index'),
    path('about/',views.function3,name='about'),
    path('policies/',views.function4,name='policies'),
    path('claims/',views.function5,name='claims'),
    path('payment/',views.function6,name='payment'),
    path('service/',views.function7,name='service'),
    path('profile/',views.function8,name='profile'),
    path('date/',views.function9,name='datetime'),
    path('settings/',views.function10,name='settings'),
    path('help/', views.function11, name='help'),
    path('qrcode/', views.function12, name='qrcode'),
    path('contactus1/', views.contactus1, name='contactus1'),
    path('sign/', views.sign, name='sign'),
    path('login/', views.checkuserlogin, name='login'),
    path('table1/', views.function14, name='table1'),
    path('ALLSQLcommands.pdf/', views.function15, name='ALLSQLcommands.pdf'),
    path('contact/', views.function16, name='contact'),
    path('404/', views.function17, name='404'),
    path('appointment/', views.function18, name='appointment'),
    path('feature/', views.function19, name='feature'),
    path('landpage/', views.function20, name='landpage'),
    path('mainabout/', views.function21, name='mainabout'),
    path('team/', views.function22, name='team'),
    path('testimonial/', views.function23, name='testimonial'),
    path('assist/', views.function24, name='assist'),

    path('termlifeinsurance/',views.policy1,name='termlifeinsurance'),
    path('healthinsurancepolicy/', views.policy2, name='healthinsurancepolicy') ,
    path('investmentplans/',views.policy3,name='investmentplans'),
    path('childsavings/', views.policy4, name='childsavings'),
    path('retirementplans/', views.policy5, name='retirementplans'),
    path('familyinsuranceplans/', views.policy6, name='familyinsuranceplans'),
    path('annuityplans/', views.policy7, name='annuityplans'),
    path('bikeinsuranceplans/', views.policy8, name='bikeinsuranceplans'),
    path('carinsuranceplans/', views.policy9, name='carinsuranceplans'),
    path('petinsuranceplans/', views.policy10, name='petinsuranceplans'),
    path('fixedmaturitypolicy/', views.policy11, name='fixedmaturitypolicy'),
    path('travelinsurancepolicy/', views.policy12, name='travelinsurancepolicy'),


]